name: Upgrade tag in appsets
description: "Set image tag in values of an application for appsets of an organization"
inputs:
  app:
    description: "The app directory name, default to repository name"
    required: false
  env:
    description: "The env directory name"
    required: true
  tag:
    description: "The tag to set, default to extracted from meta-tags inputs"
    required: false
  meta-tags:
    description: "The meta-tags inputs, required if inputs.tag is not provided"
    required: false
  commit:
    description: "Enable commit"
    required: false
  push:
    description: "Enable push"
    required: false

runs:
  using: "composite"
  steps:
  - name: 🚀 Upgrade image tag
    env:
      CD_APP: ${{ inputs.app || github.event.repository.name }}
      CD_ENV: ${{ inputs.env }}
      CD_COMMIT: ${{ inputs.commit || 'false }}
      CD_PUSH: ${{ inputs.push || 'false' }}
    shell: bash
    run: |
      TAG=${{ inputs.tag }}
      if [ -z "$TAG" ]; then
        IFS=',' read -ra TAGS_ARRAY <<< "${{ inputs.meta-tags }}"
        IMAGE=${TAGS_ARRAY[0]}
        TAG=${IMAGE##*:}
      fi

      echo "Using tag: $TAG"
      values_files="envs/$CD_ENV/$CD_APP.yaml"
      yq e '.image.tag = "'$TAG'"' -i $values_file
      git config user.name "forgejo-actions"
      git config user.email "bot@devthefuture.org"
      git add $values_files
      
      if [ "$CD_COMMIT" != "false" ]; then
        git commit --allow-empty -m "chore: set $CD_ENV/$CD_APP image.tag=$TAG"
      fi

      if [ "$CD_PUSH" != "false" ]; then
        git push origin HEAD
      fi